### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mkao006** [EST-Team-Adam/TheReadingMachine#22]
Alberto:
- [ ] Check restructured implementation of `sentiment_scoring`, and further refine to follow the repository structure.
- [ ] Improve computation performance for sentiment scoring.
- [ ] Investigate the value and magnitude of VADAR sentiments.

Marco:
- [ ] Migrate `polso` and twitter work to `thereadingmachine`.
- [ ] Check restructured implementation of geo-tagging.

Luca:
- [ ] Check restructured implementation of topic modeling.
- [ ] Improve performance of topic modeling.

Due end of May.

**Comment by marcogarieri** [comment]
I am writing this as note to myself and to whoever faces some problem with the setup.sh step.

1. Using macOS (Version 10.12.3), I was not able to install the `requirements.txt`. The main reason I was able to find is the openSSL configuration on mac. Even attempting to link the correct openssl, the `requirements.txt` are not installed.

2. Using VirtualBox and ubuntu 14.04 LTS from scratch: it is necessary to allocate more than 8GB of space, otherwise it won't be possible to install the `requirements.txt`. Using 20GB the `setup.sh` step is working, but before several packages need to be installed before entering the `virtualenv`: [this](https://stackoverflow.com/a/26333011) is the requirements. Moreover before running `python $DATA_DIR/nltk_data_downloader.py` need to call again `pip install nltk`

**Comment by marcogarieri** [comment]
The mail problem in the setup.sh script in macOS is the dependences with openssl. The main solution is to update pip: `pip install -U pip`. The first check to be done is, outside the environment to test if openssl is working opening a python terminal `python` and then trying to `import ssl`. If everything works fine it's a good beginning. Otherwise it is important to download openssl and link it (in case of brew installed: `brew install --force openssl` `brew link openssl`.
It is important that the `import ssl` in python is working as well in the `virtualenv`, it is possible that another version of python is used, thus it is important to update python in the `virtualenv`.

**Comment by marcogarieri** [comment]
Problem with the pipeline.
The pipeline does not work for the module sentiment scoring. This is the airflow log of the error.

```
[2017-05-26 11:11:10,563] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,563] {models.py:1126} INFO - Dependencies all met for <TaskInstance: the_reading_machine.sentiment_scoring 2017-05-26 11:07:29.489606 [queued]>
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,569] {models.py:1126} INFO - Dependencies all met for <TaskInstance: the_reading_machine.sentiment_scoring 2017-05-26 11:07:29.489606 [queued]>
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,569] {models.py:1318} INFO - 
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 4
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2017-05-26 11:11:10,570] {base_task_runner.py:95} INFO - Subtask: 
[2017-05-26 11:11:10,578] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,578] {models.py:1342} INFO - Executing <Task(BashOperator): sentiment_scoring> on 2017-05-26 11:07:29.489606
[2017-05-26 11:11:10,592] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,592] {bash_operator.py:71} INFO - tmp dir root location: 
[2017-05-26 11:11:10,592] {base_task_runner.py:95} INFO - Subtask: /var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T
[2017-05-26 11:11:10,594] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,593] {bash_operator.py:80} INFO - Temporary script location :/var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T/airflowtmp9ldtG4//var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T/airflowtmp9ldtG4/sentiment_scoringKONEpx
[2017-05-26 11:11:10,594] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,593] {bash_operator.py:81} INFO - Running command: python /Users/marcogarieri/Documents/TheReadingMachine/airflow/../pipeline/sentiment_scoring/sentiment_scoring.py
[2017-05-26 11:11:10,599] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:10,598] {bash_operator.py:90} INFO - Output:
[2017-05-26 11:11:11,272] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,272] {bash_operator.py:94} INFO - Traceback (most recent call last):
[2017-05-26 11:11:11,273] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,272] {bash_operator.py:94} INFO - File "/Users/marcogarieri/Documents/TheReadingMachine/airflow/../pipeline/sentiment_scoring/sentiment_scoring.py", line 5, in <module>
[2017-05-26 11:11:11,273] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,272] {bash_operator.py:94} INFO - from thereadingmachine.sentence_selector import all_sentences_analyzer
[2017-05-26 11:11:11,273] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,272] {bash_operator.py:94} INFO - ImportError: No module named thereadingmachine.sentence_selector
[2017-05-26 11:11:11,310] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,309] {bash_operator.py:97} INFO - Command exited with return code 1
[2017-05-26 11:11:11,311] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,310] {models.py:1417} ERROR - Bash command failed
[2017-05-26 11:11:11,311] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2017-05-26 11:11:11,311] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2017-05-26 11:11:11,312] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2017-05-26 11:11:11,312] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2017-05-26 11:11:11,312] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2017-05-26 11:11:11,312] {base_task_runner.py:95} INFO - Subtask: AirflowException: Bash command failed
[2017-05-26 11:11:11,312] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,312] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2017-05-26 11:11:11,321] {base_task_runner.py:95} INFO - Subtask: [2017-05-26 11:11:11,321] {models.py:1462} ERROR - Bash command failed
```

**Comment by mkao006** [comment]
Closing this issue as we have an updated list
